### ISSUE TITLE
Requirements should mention Jetpack Compose 1.2.x

### ISSUE THREAD

**Issue by gekylafas** [googlemaps/android-maps-compose#64]
This is more of a documentation oversight.
The "Requirements" and/or the "Installation" sections in README.md should mention that this SDK is only compatible with Jetpack Compose **1.2.x**.
I lost about an hour trying to make this work in my Compose 1.1.x-using project.

**Comment by jpoehnelt** [comment]
@gekylafas Thank you for opening this issue. 🙏
Please check out these other resources that might be applicable:

- [Support Console](https://cloud.google.com/support/) - If you have a support contract.
- [Discord](https://discord.gg/9UpV862xZ9) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag
- [Google Maps Platform issue trackers](https://developers.google.com/maps/support/#issue_tracker)


_This is an automated message, feel free to ignore._

**Comment by jpoehnelt** [comment]
@gekylafas Please take a moment to fill out [this short survey](https://forms.gle/wYuzN6UibnFj7ZL29). Thank you!

_This is an automated message, feel free to ignore._

**Comment by njacob1001** [comment]
I was trying to solve my app crash from this morning, thanks! I update to  jetpack compose version 1.2.0-alpha05 and now works :)

**Comment by nacro711072** [comment]
For the latest version `1.3.0`, this project need compose version 1.2.x. Otherwise, it will crash by 
```
java.lang.NoSuchMethodError: No static method isTraceInProgress()Z in class Landroidx/compose/runtime/ComposerKt
```
`1.2.0` is OK with compose version 1.1.x.

**Comment by arriolac** [comment]
Thanks for raising this. Will update the docs accordingly as well as the release notes for 1.3.0
