### ISSUE TITLE
No static method isTraceInProgress()

### ISSUE THREAD

**Issue by Eng-AhmedShehata** [googlemaps/android-maps-compose#67]
``` kotlin
java.lang.NoSuchMethodError: No static method isTraceInProgress()Z in class Landroidx/compose/runtime/ComposerKt; or its super classes (declaration of 'androidx.compose.runtime.ComposerKt' appears in /data/app/~~ex5wcn2UwF9AygGG4l0n2Q==/com.mafqud.android-qnIyQNLHppsHRjDR73AKNA==/base.apk)
        at com.google.maps.android.compose.GoogleMapKt.GoogleMap(Unknown Source:6)
        at com.mafqud.android.map.MapScreenKt.MapScreen(MapScreen.kt:33)
        at com.mafqud.android.map.ComposableSingletons$MapFragmentKt$lambda-1$1.invoke(MapFragment.kt:29)
        at com.mafqud.android.map.ComposableSingletons$MapFragmentKt$lambda-1$1.invoke(MapFragment.kt:28)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at androidx.compose.material3.TextKt.ProvideTextStyle(Text.kt:261)
        at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:76)
        at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:75)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at androidx.compose.material3.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:69)
        at com.mafqud.android.ui.theme.ThemeKt.MafQudTheme(Theme.kt:82)
        at com.mafqud.android.map.ComposableSingletons$MapFragmentKt$lambda-2$1.invoke(MapFragment.kt:28)
        at com.mafqud.android.map.ComposableSingletons$MapFragmentKt$lambda-2$1.invoke(MapFragment.kt:27)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
```

**Comment by jpoehnelt** [comment]
@Eng-AhmedShehata Thank you for opening this issue. 🙏
Please check out these other resources that might be applicable:

- [Support Console](https://cloud.google.com/support/) - If you have a support contract.
- [Discord](https://discord.gg/9UpV862xZ9) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag
- [Google Maps Platform issue trackers](https://developers.google.com/maps/support/#issue_tracker)


_This is an automated message, feel free to ignore._

**Comment by arriolac** [comment]
@Eng-AhmedShehata what version of Maps Compose are you using and what version of Jetpack Compose? Make sure you are using `1.2.x` of Compose with Maps Compose `1.3.0` and up.

**Comment by Eng-AhmedShehata** [comment]
> @Eng-AhmedShehata what version of Maps Compose are you using and what version of Jetpack Compose? Make sure you are using `1.2.x` of Compose with Maps Compose `1.3.0` and up. See [releases](https://github.com/googlemaps/android-maps-compose/releases) for more info on required Compose versions.

Thanks 
My problem solved after upgrading jetpack compose to 1.2.x

**Comment by hellosagar** [comment]
Im using 
`compose_version = '1.2.0-alpha01'` and `implementation 'com.google.maps.android:maps-compose:1.3.0'`

Still im getting this error

```
2022-04-24 19:26:52.077 9658-9658/dev.sagar.eventconcertapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.sagar.eventconcertapp, PID: 9658
    java.lang.NoSuchMethodError: No static method isTraceInProgress()Z in class Landroidx/compose/runtime/ComposerKt; or its super classes (declaration of 'androidx.compose.runtime.ComposerKt' appears in /data/data/dev.sagar.eventconcertapp/code_cache/.overlay/base.apk/classes.dex)
        at com.google.maps.android.compose.GoogleMapKt.GoogleMap(Unknown Source:6)
        at dev.sagar.eventconcertapp.presentation.detail.DetailScreenKt.DetailScreen(DetailScreen.kt:124)
        at dev.sagar.eventconcertapp.presentation.destinations.DetailScreenDestination.Content(DetailScreenDestination.kt:27)
```

**Comment by hellosagar** [comment]
Its working with `1.2.0-alpha05`
